# Generated by Django 6.0.6 on 2026-07-14 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_category_options_remove_book_price_and_more'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_user_book',
        ),
        migrations.AddField(
            model_name='cart',
            name='version_type',
            field=models.CharField(choices=[('digital', '电子版'), ('physical', '纸质版')], default='physical', max_length=10, verbose_name='版本类型'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'book', 'version_type'), name='unique_user_book_version'),
        ),
    ]
