# Generated by Django 6.0.6 on 2026-07-10 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单编号')),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收货人手机号')),
                ('receiver_address', models.CharField(max_length=200, verbose_name='收货详细地址')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '已提交'), (3, '待收货'), (4, '已完成'), (5, '已取消')], default=1, verbose_name='订单状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('ship_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('express_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号')),
                ('express_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递公司')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='订单备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(verbose_name='图书ID')),
                ('book_title', models.CharField(max_length=200, verbose_name='图书名称')),
                ('book_cover', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图')),
                ('book_author', models.CharField(max_length=100, verbose_name='作者')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='下单时售价')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order_items',
            },
        ),
    ]
