# Generated by Django 6.0.6 on 2026-07-14 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_category_options_remove_book_price_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='version_type',
            field=models.CharField(choices=[('digital', '电子版'), ('physical', '纸质版')], default='physical', max_length=10, verbose_name='版本类型'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DigitalBookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_purchases', to='books.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_purchases', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '电子书购买记录',
                'verbose_name_plural': '电子书购买记录',
                'db_table': 'digital_book_purchases',
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_digital_book')],
            },
        ),
    ]
