# Generated by Django 6.0.6 on 2026-07-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN编号')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定价')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图链接')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图书简介')),
                ('catalog', models.TextField(blank=True, null=True, verbose_name='目录')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'db_table': 'books',
                'indexes': [models.Index(fields=['title', 'author'], name='books_title_e8b1ad_idx'), models.Index(fields=['isbn'], name='books_isbn_ce4a1a_idx')],
            },
        ),
    ]
