# Generated by Django 6.0.6 on 2026-07-07 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_shelf_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='上架日期'),
        ),
    ]
