# Generated by Django 6.0.6 on 2026-07-14 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_on_shelf_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '图书分类'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
        migrations.AddField(
            model_name='book',
            name='content_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='全文文件路径'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='总销量'),
        ),
        migrations.CreateModel(
            name='BookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('digital', '电子版'), ('physical', '纸质版')], max_length=10, verbose_name='版本类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定价')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='是否在售')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='books.book', verbose_name='所属图书')),
            ],
            options={
                'verbose_name': '图书版本',
                'verbose_name_plural': '图书版本',
                'db_table': 'book_versions',
                'constraints': [models.UniqueConstraint(fields=('book', 'version_type'), name='unique_book_version_type')],
            },
        ),
    ]
