# Generated by Django 6.0.6 on 2026-07-10 23:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_book_on_shelf_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsed_by', to='books.book', verbose_name='浏览图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_histories', to=settings.AUTH_USER_MODEL, verbose_name='浏览用户')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史',
                'db_table': 'browsing_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book', verbose_name='收藏图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
            options={
                'verbose_name': '图书收藏',
                'verbose_name_plural': '图书收藏',
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_favorite')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分（1~5星）')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='评价图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': '图书评价',
                'verbose_name_plural': '图书评价',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_review')],
            },
        ),
    ]
