import { request } from './client'
import { resolveMediaUrl } from './normalizers'

const validId = (value, label = '用户 ID') => { const id = Number(value); if (!Number.isSafeInteger(id) || id <= 0) throw new Error(`${label} 不能为空或无效`); return id }
const normalizeAdminUser = value => ({ id: Number.isSafeInteger(Number(value?.id)) ? Number(value.id) : null, username: typeof value?.username === 'string' ? value.username : '', phone: typeof value?.phone === 'string' ? value.phone : '', email: typeof value?.email === 'string' ? value.email : '', avatar: resolveMediaUrl(value?.avatar), gender: value?.gender === 'M' ? '男' : value?.gender === 'F' ? '女' : '未设置', isActive: Boolean(value?.is_active), isStaff: Boolean(value?.is_staff), isSuperuser: Boolean(value?.is_superuser) })

const money = value => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null }
const presentUser = value => {
  if (value && typeof value === 'object') return value.username || value.name || `用户 ID：${value.id ?? '未知'}`
  if (typeof value === 'number') return `用户 ID：${value}`
  return value ? String(value) : '未知用户'
}
const normalizeItem = value => ({ id:value?.id ?? null, bookId:value?.book_id ?? null, title:value?.book_title ?? '', coverImage:resolveMediaUrl(value?.book_cover), author:value?.book_author ?? '', salePrice:money(value?.sale_price), quantity:Number.isFinite(Number(value?.quantity)) ? Number(value.quantity) : 0, subtotal:money(value?.subtotal), versionType:value?.version_type ?? '', versionLabel:value?.version_label ?? value?.version_type ?? '' })
const normalizeOrder = value => ({ id:value?.id ?? null, orderNo:value?.order_no ?? '', user:presentUser(value?.user), receiver:value?.receiver ?? '', receiverPhone:value?.receiver_phone ?? '', receiverAddress:value?.receiver_address ?? '', remark:value?.remark ?? '', status:value?.status ?? null, statusText:value?.status_text ?? '', totalAmount:money(value?.total_amount), payAmount:money(value?.pay_amount), createdAt:value?.created_at ?? null, payTime:value?.pay_time ?? null, shipTime:value?.ship_time ?? null, receiveTime:value?.receive_time ?? null, cancelTime:value?.cancel_time ?? null, expressNo:value?.express_no ?? '', expressCompany:value?.express_company ?? '', items:Array.isArray(value?.items) ? value.items.map(normalizeItem) : [] })
const normalizeBookVersion = value => ({ id: Number.isSafeInteger(Number(value?.id)) ? Number(value.id) : null, versionType: value?.version_type === 'physical' ? 'physical' : 'digital', versionLabel: value?.version_type === 'physical' ? '纸质版' : '电子版', price: money(value?.price), salePrice: money(value?.sale_price), stock: Number.isSafeInteger(Number(value?.stock)) && Number(value.stock) >= 0 ? Number(value.stock) : 0, isOnSale: Boolean(value?.is_on_sale) })
const normalizeAdminBook = value => ({ id: Number.isSafeInteger(Number(value?.id)) ? Number(value.id) : null, title: typeof value?.title === 'string' ? value.title : '', author: typeof value?.author === 'string' ? value.author : '', isbn: typeof value?.isbn === 'string' ? value.isbn : '', publisher: typeof value?.publisher === 'string' ? value.publisher : '', publishDate: value?.publish_date || '', coverImage: resolveMediaUrl(value?.cover_image), description: typeof value?.description === 'string' ? value.description : '', catalog: typeof value?.catalog === 'string' ? value.catalog : '', contentFilePath: typeof value?.content_file_path === 'string' ? value.content_file_path : '', categoryId: Number.isSafeInteger(Number(value?.category)) ? Number(value.category) : null, categoryName: typeof value?.category_name === 'string' ? value.category_name : '', isOnSale: Boolean(value?.is_on_sale), salesCount: Number.isFinite(Number(value?.sales_count)) ? Number(value.sales_count) : 0, rating: money(value?.rating), onShelfDate: value?.on_shelf_date || '', createdAt: value?.created_at || '', updatedAt: value?.updated_at || '', hasContent: Boolean(value?.has_content), contentAvailable: Boolean(value?.content_available), versions: Array.isArray(value?.versions) ? value.versions.map(normalizeBookVersion) : [] })
const normalizeAdminCategory = value => ({ id: Number.isSafeInteger(Number(value?.id)) ? Number(value.id) : null, name: typeof value?.name === 'string' ? value.name : '', parent: Number.isSafeInteger(Number(value?.parent)) ? Number(value.parent) : null, parentName: typeof value?.parent_name === 'string' ? value.parent_name : '', sort: Number.isSafeInteger(Number(value?.sort)) && Number(value.sort) >= 0 ? Number(value.sort) : 0, description: typeof value?.description === 'string' ? value.description : '', isActive: Boolean(value?.is_active), bookCount: Number.isSafeInteger(Number(value?.book_count)) && Number(value.book_count) >= 0 ? Number(value.book_count) : 0, childCount: Number.isSafeInteger(Number(value?.child_count)) && Number(value.child_count) >= 0 ? Number(value.child_count) : 0 })

export async function getAdminOrders(filters = {}) { const params = {}; if (filters.status !== undefined && filters.status !== null && filters.status !== '') params.status = filters.status; if (String(filters.orderNo ?? '').trim()) params.order_no = String(filters.orderNo).trim(); if (String(filters.receiver ?? '').trim()) params.receiver = String(filters.receiver).trim(); const response = await request('/admin/orders/', { params }); return (response?.data ?? []).map(normalizeOrder) }
export async function getAdminUsers(filters = {}) { const params = {}; const keyword = String(filters.keyword ?? '').trim(), page = Number(filters.page), pageSize = Number(filters.pageSize); if (keyword) params.keyword = keyword; if (Number.isSafeInteger(page) && page > 0) params.page = page; if (Number.isSafeInteger(pageSize) && pageSize > 0 && pageSize <= 100) params.page_size = pageSize; const response = await request('/admin/users/', { params }); const data = response?.data ?? {}; return { total: Number.isFinite(Number(data.total)) && Number(data.total) >= 0 ? Number(data.total) : 0, page: Number.isSafeInteger(Number(data.page)) && Number(data.page) > 0 ? Number(data.page) : 1, pageSize: Number.isSafeInteger(Number(data.page_size)) && Number(data.page_size) > 0 ? Number(data.page_size) : 20, items: Array.isArray(data.items) ? data.items.map(normalizeAdminUser) : [] } }
export async function getAdminUserDetail(userId) { const id = validId(userId); const response = await request(`/admin/users/${encodeURIComponent(id)}/`); return normalizeAdminUser(response?.data) }
export async function toggleAdminUser(userId, isActive) { const id = validId(userId); const response = await request(`/admin/users/${encodeURIComponent(id)}/toggle/`, { method: 'PUT', body: { is_active: Boolean(isActive) } }); return normalizeAdminUser({ ...(response?.data ?? {}), id }) }
export async function getAdminOrderDetail(orderId) { if (orderId === undefined || orderId === null || orderId === '') throw new Error('订单 ID 不能为空'); const response = await request(`/admin/orders/${encodeURIComponent(orderId)}/`); return normalizeOrder(response?.data) }
export async function shipAdminOrder(orderId, payload) { if (orderId === undefined || orderId === null || orderId === '') throw new Error('订单 ID 不能为空'); const response = await request(`/admin/orders/${encodeURIComponent(orderId)}/action/`, { method:'PUT', body:{ action:'ship', express_no:payload?.expressNo, express_company:payload?.expressCompany } }); return normalizeOrder(response?.data) }
export async function getAdminBooks(filters = {}) { const params = {}; const keyword = String(filters.keyword ?? '').trim(), category = Number(filters.category), page = Number(filters.page), pageSize = Number(filters.pageSize); if (keyword) params.keyword = keyword; if (Number.isSafeInteger(category) && category > 0) params.category = category; if (filters.isOnSale === true || filters.isOnSale === false) params.is_on_sale = String(filters.isOnSale); if (Number.isSafeInteger(page) && page > 0) params.page = page; if (Number.isSafeInteger(pageSize) && pageSize > 0 && pageSize <= 100) params.page_size = pageSize; const response = await request('/admin/books/', { params }); const data = response?.data ?? {}; return { total: Number.isFinite(Number(data.total)) && Number(data.total) >= 0 ? Number(data.total) : 0, page: Number.isSafeInteger(Number(data.page)) && Number(data.page) > 0 ? Number(data.page) : 1, pageSize: Number.isSafeInteger(Number(data.page_size)) && Number(data.page_size) > 0 ? Number(data.page_size) : 20, items: Array.isArray(data.items) ? data.items.map(normalizeAdminBook) : [] } }
export async function getAdminBookDetail(bookId) { const id = validId(bookId, '图书 ID'); const response = await request(`/admin/books/${encodeURIComponent(id)}/`); return normalizeAdminBook(response?.data) }
export async function getAdminCategories() { const response = await request('/admin/categories/'); return Array.isArray(response?.data) ? response.data.map(normalizeAdminCategory) : [] }
export async function createAdminCategory(payload) { const response = await request('/admin/categories/', { method:'POST', body:payload }); return normalizeAdminCategory(response?.data) }
export async function updateAdminCategory(categoryId, payload) { const id = validId(categoryId, '分类 ID'); const response = await request(`/admin/categories/${encodeURIComponent(id)}/`, { method:'PUT', body:payload }); return normalizeAdminCategory(response?.data) }
export async function deleteAdminCategory(categoryId) { const id = validId(categoryId, '分类 ID'); const response = await request(`/admin/categories/${encodeURIComponent(id)}/`, { method:'DELETE' }); return { affectedBooks:Number.isSafeInteger(Number(response?.data?.affected_books)) ? Number(response.data.affected_books) : 0 } }
export async function getAdminCategoryBooks(categoryId, filters = {}) { const id = validId(categoryId, '分类 ID'), params = {}; const keyword = String(filters.keyword ?? '').trim(), page = Number(filters.page), pageSize = Number(filters.pageSize); if (keyword) params.keyword = keyword; if (Number.isSafeInteger(page) && page > 0) params.page = page; if (Number.isSafeInteger(pageSize) && pageSize > 0 && pageSize <= 100) params.page_size = pageSize; const response = await request(`/admin/categories/${encodeURIComponent(id)}/books/`, { params }); const data = response?.data ?? {}; return { total:count(data.total), page:Number.isSafeInteger(Number(data.page)) && Number(data.page) > 0 ? Number(data.page) : 1, pageSize:Number.isSafeInteger(Number(data.page_size)) && Number(data.page_size) > 0 ? Number(data.page_size) : 20, items:Array.isArray(data.items) ? data.items.map(normalizeAdminBook) : [] } }
export async function updateAdminCategoryBooks(categoryId, action, bookIds) { const id = validId(categoryId, '分类 ID'); if (!['add','remove'].includes(action)) throw new Error('分类图书操作无效'); const ids = [...new Set((bookIds ?? []).map(Number))]; if (!ids.length || ids.some(value => !Number.isSafeInteger(value) || value <= 0)) throw new Error('请选择有效图书'); const response = await request(`/admin/categories/${encodeURIComponent(id)}/books/`, { method:'PUT', body:{ action, book_ids:ids } }); return { changed:count(response?.data?.changed), category:normalizeAdminCategory(response?.data?.category) } }
export async function createAdminBook(payload) { const response = await request('/admin/books/', { method: 'POST', body: payload }); return normalizeAdminBook(response?.data) }
export async function updateAdminBook(bookId, payload) { const id = validId(bookId, '图书 ID'); const response = await request(`/admin/books/${encodeURIComponent(id)}/`, { method: 'PUT', body: payload }); return normalizeAdminBook(response?.data) }
export async function setAdminBookSale(bookId, isOnSale) { const id = validId(bookId, '图书 ID'); const response = await request(`/admin/books/${encodeURIComponent(id)}/sale/`, { method: 'PUT', body: { is_on_sale: Boolean(isOnSale) } }); return normalizeAdminBook(response?.data) }
const count = value => Number.isSafeInteger(Number(value)) && Number(value) >= 0 ? Number(value) : 0
export async function getAdminDashboardSummary() { const response = await request('/admin/dashboard/summary/'); const data = response?.data ?? {}, group = value => ({ total:count(value?.total), active:count(value?.active), disabled:count(value?.disabled), staff:count(value?.staff), onSale:count(value?.on_sale), offSale:count(value?.off_sale), digitalVersions:count(value?.digital_versions), physicalVersions:count(value?.physical_versions), pending:count(value?.pending), submitted:count(value?.submitted), shipped:count(value?.shipped), completed:count(value?.completed), cancelled:count(value?.cancelled) }); return { users:group(data.users), books:group(data.books), orders:group(data.orders), sales:{ paidOrderCount:count(data.sales?.paid_order_count), paidAmount:money(data.sales?.paid_amount), physicalQuantity:count(data.sales?.physical_quantity), digitalQuantity:count(data.sales?.digital_quantity) }, lowStock:Array.isArray(data.low_stock) ? data.low_stock.map(x => ({ versionId:count(x?.version_id), bookId:count(x?.book_id), bookTitle:typeof x?.book_title === 'string' ? x.book_title : '', stock:Number.isSafeInteger(Number(x?.stock)) ? Number(x.stock) : 0, isOnSale:Boolean(x?.is_on_sale) })) : [], recentOrders:Array.isArray(data.recent_orders) ? data.recent_orders.map(x => ({ id:count(x?.id), orderNo:typeof x?.order_no === 'string' ? x.order_no : '', username:typeof x?.username === 'string' ? x.username : '', receiver:typeof x?.receiver === 'string' ? x.receiver : '', status:count(x?.status), statusText:typeof x?.status_text === 'string' ? x.status_text : '', payAmount:money(x?.pay_amount), createdAt:x?.created_at || '' })) : [] } }
