import { request } from './client'
import { resolveMediaUrl } from './normalizers'
const money = value => { const n = Number(value); return Number.isFinite(n) ? n : null }
const item = x => ({ id:x.id, bookId:x.book_id, title:x.book_title||'', coverImage:resolveMediaUrl(x.book_cover), author:x.book_author||'', salePrice:money(x.sale_price), quantity:x.quantity, subtotal:money(x.subtotal), versionType:x.version_type, versionLabel:x.version_label||x.version_type })
const order = x => ({ id:x.id, orderNo:x.order_no, status:x.status, statusText:x.status_text||'', totalAmount:money(x.total_amount), payAmount:money(x.pay_amount), receiver:x.receiver||'', receiverPhone:x.receiver_phone||'', receiverAddress:x.receiver_address||'', remark:x.remark||'', createdAt:x.created_at||null, updatedAt:x.updated_at||null, payTime:x.pay_time||null, shipTime:x.ship_time||null, receiveTime:x.receive_time||null, cancelTime:x.cancel_time||null, expressNo:x.express_no||'', expressCompany:x.express_company||'', itemCount:x.item_count??(x.items||[]).length, items:(x.items||[]).map(item) })
export async function getOrders(status) { if(status!==undefined&&status!==null&&status!==''&&!([1,2,3,4,5].includes(Number(status)))) throw new Error('不支持的订单状态'); const r=await request('/orders/',{params:status?{status}:{}}); return (r.data||[]).map(order) }
export async function getOrderDetail(id) { if(id===undefined||id===null||id==='') throw new Error('获取订单详情需要订单 ID'); return order((await request(`/orders/${id}/`)).data) }
export async function createOrder(payload) { return order((await request('/orders/',{method:'POST',body:{address:payload.address,receiver:payload.receiver,phone:payload.phone,cart_item_ids:payload.cartItemIds,remark:payload.remark}})).data) }
export async function operateOrder(id,action) { if(!['pay','cancel','confirm'].includes(action)) throw new Error('不支持的订单操作'); return order((await request(`/orders/${id}/`,{method:'PUT',body:{action}})).data) }
export async function getBookshelf() { const r=await request('/orders/bookshelf/'); return (r.data||[]).map(x=>({bookId:x.book_id,title:x.title||'',author:x.author||'',coverImage:resolveMediaUrl(x.cover_image),purchasedAt:x.purchased_at||null,canRead:Boolean(x.can_read),hasContent:Boolean(x.has_content),isOnSale:x.is_on_sale!==false})) }
